chore: add pdf comparison acthions

diff --git a/.github/workflows/docker-build.yaml b/.github/workflows/docker-build.yaml
--- a/.github/workflows/docker-build.yaml
+++ b/.github/workflows/docker-build.yaml
@@ -40,7 +40,7 @@ jobs:
       - name: Check image
         run: |
           cd sample
-          docker run --rm -v $(pwd):/latex ${{steps.metadata.outputs.tags}} sh -c \
+          docker run --rm -v $(pwd):/latex ${{steps.metadata.outputs.tags}} bash -c \
             "ptex2pdf -u -l -ot '-kanji=utf8 -synctex=1 -interaction=nonstopmode' sample.tex && \
             pbibtex sample && \
             ptex2pdf -u -l -ot '-kanji=utf8 -synctex=1 -interaction=nonstopmode' sample.tex && \
@@ -51,3 +51,72 @@ jobs:
         with:
           name: pdf-artifact
           path: sample/sample.pdf
+  pdf-comparison:
+    runs-on: ubuntu-latest
+    needs: build
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v4
+
+      - name: Download PDF artifact
+        uses: actions/download-artifact@v4
+        with:
+          name: pdf-artifact
+          path: tmp
+
+      - name: Set up Docker Buildx
+        uses: docker/setup-buildx-action@v3
+
+      - name: Cache Docker layers
+        uses: actions/cache@v4
+        with:
+          path: /tmp/.buildx-cache
+          key: ${{ runner.os }}-buildx-${{ github.sha }}
+          restore-keys: |
+            ${{ runner.os }}-buildx-
+
+      - name: Build pdf-to-image
+        run: make buildx.pdf
+
+      - name: Convert PDF to PNG
+        run: |
+          docker run --rm -v $(pwd):/pdf pdf bash -c "pdftoppm -png sample/sample.pdf tmp/ref"
+
+          docker run --rm -v $(pwd):/pdf pdf bash -c "pdftoppm -png tmp/sample.pdf tmp/act"
+
+          ls tmp
+
+      - name: Compare PNG
+        run: |
+          PAGE_COUNT_REF=$(ls tmp/ref-*.png | wc -l)
+          PAGE_COUNT_ACT=$(ls tmp/act-*.png | wc -l)
+
+          if [ $PAGE_COUNT_REF -ne $PAGE_COUNT_ACT ]; then
+            echo "Error: Page count mismatch $PAGE_COUNT_REF != $PAGE_COUNT_ACT"
+            exit 1
+          fi
+
+          DIFF_COUNT=0
+
+          for i in $(seq 1 $PAGE_COUNT_REF); do
+            docker run --rm -v $(pwd)/tmp:/pdf pdf bash -c "compare -metric RMSE ref-$i.png act-$i.png diff-$i.png 2>&1"
+
+            echo "Page $i: $?"
+            if [ $? -ne 0 ]; then
+              DIFF_COUNT=$((DIFF_COUNT+1))
+            fi
+          done
+
+          if [ $DIFF_COUNT -ne 0 ]; then
+            echo "Error: $DIFF_COUNT pages are different"
+            exit 1
+          else
+            echo "All pages are the same"
+          fi
+
+      - name: Upload diff as artifact
+        if: ${{ failure() }}
+        uses: actions/upload-artifact@v4
+        with:
+          name: diff-artifact
+          path: tmp
